# Generated by Django 4.0 on 2021-12-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placebet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('wallet', models.IntegerField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bet',
            name='solution',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='betanswer',
            name='value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
